config/routes.rb
Rails.application.routes.draw do
  get 'articles/search'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }
  resources :categories
  resources :articles do
    resources :comments
  end
  # get 'articles/new'
  # get 'articles/show'
  # get 'articles/index'
  # get 'welcome/index'ç
  post 'contacts/new'
  get 'welcome/contacto'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article, only: [:update, :destroy, :create, :edit]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    redirect_to root_path
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @article.comments.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'El comentario fué creado.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'El comentario fué actualizado.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'El comentario fué eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def set_article
      @article = Article.find(params[:article_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :user_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@article,comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="form-group row">
    <%#= form.label :body, class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
    <%= form.text_area :body, id: :comment_body, class:"col-md-12 form-control" %>
  </div>

  <div class="form-group row">
    <div class="container text-right">
      <%= form.submit "Comentar", class:"btn btn-outline-success col-md-3" %>
  </div>
<% end %>

app/views/comments/_form_edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <br>
      <div class="jumbotro space-a">
        <fieldset>
          <legend class="text-center space-title form-title">
            Editar Comentario
          </legend>
          <%= form_with(model: [@article,comment], local: true) do |form| %>
            <% if comment.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                <ul>
                  <% comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <br>
            <div class="form-group row">
              <%#= form.label :body, class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
              <%= form.text_area :body, id: :comment_body, class:"col-md-12 form-control" %>
            </div>

            <div class="form-group row">
              <div class="container text-right">
                <%= form.submit "Comentar", class:"btn btn-outline-success col-md-3" %>
              </div>
          <% end %>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form_edit', comment: @comment, title:"Editar" %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article %></td>
        <td><%= comment.user %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment.article %></td>
        <td><%= link_to 'Edit', article_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <br>
      <div class="jumbotron space-a">
        <fieldset>
          <legend class="text-center space-title form-title">
            <%= "#{@article.title} Categoria" %>
            <%= render 'form', comment: @comment %>
          </legend>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>