config/routes.rb
Rails.application.routes.draw do
  get 'articles/search'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }
  resources :categories
  resources :articles do
    resources :comments
  end
  # get 'articles/new'
  # get 'articles/show'
  # get 'articles/index'
  # get 'welcome/index'ç
  post 'contacts/new'
  get 'welcome/contacto'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
  
end

app/models/article.rb
class Article < ApplicationRecord
  include PermissionsConcern
  has_many :comments
  has_many :has_categories
  has_many :categories, through: :has_categories
  after_create :save_categories
  belongs_to :user
  validates :title, uniqueness: true
  validates :title, :body, presence: true
  validates :title, length: { in: 5..25 }
  validates :body, length: { minimum: 100, too_short: "Mínimo son %{count} caracteres." }
  validate :validate_categories
  # scope :my_scope, -> (query) { }
  scope :ultimos, -> { order("created_at ASC") }
  scope :ult, -> { where(title:"prueba") }

  # scope :titulo, -> (find_titulo) { where title: find_titulo }
  scope :titulo, -> (title) { where("title LIKE ?", "%#{title}%") }

  has_attached_file :img_art, 
    styles: { 
      thumb:  { geometry: '320x240>',   format: :png, convert_options: '-background "#c0c0" -gravity center -extent 320x240' },
      thumb2: { geometry: '320x240#',   format: :png, convert_options: '-background white -gravity center -extent 320x240' },
      medium: { geometry: '300x300>',   format: :png, convert_options: '-background white -gravity center -extent 300x300' },
      big:    { geometry: '500x500>',   format: :png, convert_options: '-background white -gravity center -extent 500x500' },
      hd:     { geometry: '1920x1080',  format: :png, convert_options: '-background white -gravity center -extent 1920x1080' }, #80x60
      ban:    { geometry: '630x315>',   format: :png, convert_options: '-background white -gravity center -extent 630x315'  }
    }, 
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_art, content_type: /\Aimage\/.*\z/

  def categories=(value)
    @categories = value
    # raise @categories.to_yaml
  end

  def getCategories
    @categories
  end

  private
  def save_categories
    @categories.each do |category_id|
      # raise "category_id #{category_id} article_id #{self.id}"
      HasCategory.create(category_id: category_id, article_id: self.id)
    end
  end

  def validate_categories
    if self.getCategories.blank?
      errors.add(:categories, "Debe agregar una categoria.")
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  before_action :authenticate_editor!, only: [:edit, :update, :create, :new]
  before_action :authenticate_admin!, only: [:create, :new, :edit, :update, :destroy]

  def search  
    if params.has_key?(:titulo) && !params[:titulo].empty?
      # @articles = Article.where("title LIKE ?", "%#{params[:titulo]}%")
      @articles = Article.titulo(params[:titulo])
    else
      @articles = Article.all
    end 
  end

  def index
    @articulos = Article.paginate(:page => params[:page], :per_page => 8).ultimos
    if user_signed_in? && current_user.permission_level >= 1 && !params.has_key?(:cambiar)
      render :admin_article
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @article = Article.new
    @categories = Category.all
    # raise @article.to_yaml
  end

  def create
    # if params[:categories].nil?
    #   redirect_to new_article_path, alert:"Necesitas seleccionar al menos una categoría"
    # else
      @article = current_user.articles.new(article_params)
      @article.categories = params[:categories]
      # raise @article.to_yaml
      # raise current_user.to_yaml
      # raise params.to_yaml
      respond_to do |format|
        if @article.save
          format.html {redirect_to @article, notice: "El artículo #{@article.title} fué creado"}
          format.json {render :show, status: :created, location: @article}
        else
          format.html { render :new }
          format.json { render json: @article.errors, status: :unprocessable_entry}
        end
      end
    # end
  end

  def edit  
  end

  def update
    @article.categories = @article.categories.ids
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "El artículo #{@article.title} fué modificado." }
        format.json {render :show, status: :created, location: @article}
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entry}
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_path, notice: "El artículo fué eliminado" }
      format.json { head :no_content}
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :categories, :img_art)
  end
  def set_article
    begin
      @article = Article.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert: "No existe ese articulo."
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="col-12 col-sm-6 col-md-4 col-lg-3 article-salto">
  <div class="card h-100 article-container" >
    <div class="card-body card-body2">
        <%= image_tag article.img_art(:thumb), class:"card-img-top" %>
        <h3 class="card-title text-center">
            <%= link_to truncate(article.title, length:20), article, class:"no-color-link" %>
        </h3>
        <p>
          <%= truncate_html(article.body.html_safe, length:100) %>
        </p>
        <% temporal = "" %>
        <% article.categories.each do |category| %>
          <% temporal = "#{temporal} #{category.name}" %>
        <% end %>
        <p>
          <%= "Categoria(s): #{temporal}"  %>
        </p>
        <% if user_signed_in? %>
          <div class="text-center">
            <% if current_user.permission_level >= 1 %>
              <%= link_to  'Editar', edit_article_path(article), class:'btn btn-outline-warning' %>
            <% end %>
            <% if current_user.is_admin? %>
              <%= link_to "Eliminar", article, method: :delete, data: {confirm: 'Esta seguro que desea eliminar el article?'}, class:'btn btn-outline-danger' %>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <br>
      <div class="jumbotro space-a">
        <fieldset>
          <legend class="text-center space-title form-title">
            <%= "#{title} articulo" %>
          </legend>
          <% if article.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(article.errors.count, "error") %> prohibited this category from being saved:</h2>
            <ul>
              <% article.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <%= form_with(model: article, local: true) do |form| %>
            <div class="form-group row">
              <%= form.label "Titulo:", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
              <%= form.text_field :title, class:"col-md-4 form-control" %>
            </div>
            <div class="form-group row">
              <%= form.label "Banner:", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
              <%= form.file_field :img_art, class:"col-md-4 form-control" %>
            </div>
            <%= form.trix_editor :body, as: :trix_editor %>
            <% Category.all.each do |category| %>
              <%= check_box_tag "categories[]", category.id %>
              <%= category.name %> <br>
            <% end %>
            <div class="form-group">
              <div class="container text-center">
                <%= form.submit "Aceptar", class:"btn btn-outline-success col-md-3" %>
                <%= link_to  "Cancelar", :back, class: "btn btn-outline-info col-md-3" %>
              </div>
            </div>
          <% end %>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/articles/admin_article.html.erb
<style type="text/css" media="screen">
  .jumbotron{
    padding-top: 10px !important;
  }
</style>

<div class="jumbotron table-responsive">
  <h1>Administrador</h1>
  <%= link_to  "Cambiar vista", articles_path(cambiar:true), class:"btn btn-info" %>
  <table class="table-responsive">
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-primary">
          <th>#</th>
          <th>Título</th>
          <th>Fecha de creación</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @articulos.each do |art| %>
        <tr>
          <td>
            <%= art.id %>
          </td>
          <td>
            <%= art.title %>
          </td>
          <td>
            <%= art.created_at.strftime("%d/%m/%Y %H:%M") %>
          </td>
          <td>
            <%= link_to "Ver", art, class:"btn btn-outline-info" %>
            <%= link_to "Editar", edit_article_path(art), class:"btn btn-outline-warning" %>
            <%= link_to "Eliminar", art, method: :delete, data:{confirm:"Desea eliminar?"}, class:"btn btn-outline-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </table>

  <div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
    <%= will_paginate @articulos %>
  </div>

</div>

app/views/articles/edit.html.erb
<%= render "form", article: @article, title:"Editar" %>

app/views/articles/index.html.erb
<% @default_title = "Indice de Articulos" %>

<!-- <h2><%= link_to  "Nuevo Artículo", new_article_path, class:"btn btn-success" %></h2> -->

<div class="container-fluid">
    <div class="row justify-content-center">
        <%= render @articulos %>
      </div>      
</div>

<div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
  <%= will_paginate @articulos %>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article, title:"Nuevo" %>

app/views/articles/search.html.erb
<div class="jumbotron">
  <% if !@articles.blank? %>
    <table class="table table-hover text-center">
      <thead>
        <tr>
          <th scope="col">Artículo</th>
          <th scope="col" class="text-center">Descripción</th>
          <th scope="col">Opción</th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |art| %>
          <tr class="table-primary">
            <th scope="row"><%= link_to art.title, art, class:"no-color-link" %></th>
            <td><%= truncate_html(art.body, length:100) %></td>
            <td><%= link_to "Ver más", art, class:"btn btn-info" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-center">El buscador no encontró ninguna coincidencia para <%= "'#{params[:titulo]}'" %>. Intenta nuevamente.</p>
  <% end %>
</div>

app/views/articles/show.html.erb
<% @default_title = 'Visualización' %>

 <%#= @article.inspect %>


  <div class='jumbotron'>

    <div class="row">
      <div class="col-md-6 offset-md-3 col-12">
        <div class="text-center">
          <%= image_tag @article.img_art :thumb %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 offset-md-3 col-12">
        <h1 class="text-center">
          <%= @article.title %>
        </h1>
        <% if !@article.user.nil? %>
          <br>
          <p class="text-center">
            Creado por: <strong><%= @article.user.email %></strong>
          </p>
        <% end %>
        <div class="text-center">
          <% @article.categories.each do |category| %>
            <span class="badge badge-primary">
              <%= link_to category.name, category, class:'no-color-link', style:'color:#fff; font-size:14px;' %>
            </span>
          <% end %>
        </div>
        <br>
        <div class="article-html">
          <%= @article.body.html_safe %>
          <% if user_signed_in? %>
            <%= render 'comments/form', comment: @comment  %>
          <% end %>
        </div>
        <h4 style="margin-top: 25px;"><ins>Comentarios</ins></h4>
        <ul style="background:none; margin-top:0px;">
          <% @article.comments.each do |comment| %>
            <li>
              <div class="row justify-content-between align-items-center">
                  <div class="col-md-6" style="font-size: 12px;">
                    <%= comment.user.email %>: <%= comment.body %>
                  </div>
                  <% if user_signed_in? && current_user == comment.user %>
                    <div class="col-4 align-self-end">
                      <%= link_to "Editar", edit_article_comment_url(@article,comment), class:'btn btn-warning', style:"font-size: 12px !important;" %>
                      <%= link_to "Eliminar", [@article,comment], method: :delete, data:{confirm: "Estas seguro?"}, class:'btn btn-danger', style:"font-size: 12px !important;" %>
                    </div>
                    <% end %>
                </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>