config/routes.rb
Rails.application.routes.draw do
  get 'articles/search'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }
  resources :categories
  resources :articles do
    resources :comments
  end
  # get 'articles/new'
  # get 'articles/show'
  # get 'articles/index'
  # get 'welcome/index'ç
  post 'contacts/new'
  get 'welcome/contacto'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
  
end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="padding-bottom: 2px; padding-top: 1px;">
  <a class="navbar-brand" href="#">Mi Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to  "Inicio", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contacto", new_contact_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
        <%= link_to  "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"nav-link" %>
      <% else %>
        <%= link_to "Iniciar Sesión", new_user_session_path, class:"nav-link" %>
        <%= link_to "Registrarse", new_user_registration_path, class:"nav-link" %>
      <% end %>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <%= form_tag articles_search_path, :method => 'get', class:"form-inline my-2 my-lg-0" do %>
        <%= text_field_tag :titulo, params[:titulo], class:"form-control form-control-a my-sm-0", placeholder:"Busqueda" %>
        <%= submit_tag "Buscar", :name => nil, class:"btn btn-secondary my-2 my-sm-0 btn-a text-center" %>
    <% end %>
  </div>
</nav>

app/views/partials/_notifications.html.erb
<% if !notice.nil? %>
  <div class="alert alert-dismissible alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>
<% if !alert.nil? %>
  <div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4 class="alert-heading">Atencion!</h4>
    <%= alert %>
  </div>
<% end %>

app/views/partials/_panel.html.erb
<% if user_signed_in? %>
  <% if current_user.permission_level >= 1 %>
    <div class="list-group w-100">
      <%= link_to "Administración", root_path, class: "list-group-item list-group-item-action active" %>
      <%= link_to "Ver artículo", articles_path, class:"list-group-item list-group-item-action" %>
      <%= link_to "Crear artículo", new_article_path, class:"list-group-item list-group-item-action" %>
      <%= link_to "Ver categoría", categories_path, class:"list-group-item list-group-item-action" %>
      <%= link_to "Crear categoría", new_category_path, class:"list-group-item list-group-item-action" %>
    </div>
  <% end %>
<% end %>

<div class="list-group">
    <%= link_to "Categorias", categories_path, class: "list-group-item list-group-item-action active" %>
    <% @categorias.each do |categoria| %>
      <%= link_to  "#{categoria.name}", categoria, class:"list-group-item list-group-item-action" %>
    <% end %>
</div>