config/routes.rb
Rails.application.routes.draw do
  get 'articles/search'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }
  resources :categories
  resources :articles do
    resources :comments
  end
  # get 'articles/new'
  # get 'articles/show'
  # get 'articles/index'
  # get 'welcome/index'ç
  post 'contacts/new'
  get 'welcome/contacto'
  resources :contacts, only: [:create, :new]
  root 'articles#index'
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :has_categories
  has_many :articles, through: :has_categories
  belongs_to :user
  validates :name, uniqueness: true
  validates :name, :color, presence: true
  validates :name, length: { in: 7..20 }
  validates :color, length: { in: 4..7 }

  has_attached_file :cat_img,
    styles:{
      medium: { geometry: '256x170>', format: :png, convert_options: '-background "#c0c0" -gravity center -extent 256x170' }
    },
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cat_img, content_type: /\Aimage\/.*\z/

end

app/controllers/categories_controller.rb
 class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  before_action :authenticate_editor!, only: [:create, :new, :edit, :update]
  before_action :authenticate_admin!, only: [:create, :new, :edit, :update, :destroy]


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    if user_signed_in? && current_user.permission_level >= 1 && !params.has_key?(:cambiar)
      render :admin_category
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @articles = @category.articles.paginate(:page => params[:page], :per_page => 4)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'La categoría fué creada.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'La categoría fué actualizada.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'La categoría fué eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      begin
        @category = Category.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, alert: "No existe esa categoría"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color, :cat_img)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<style type="text/css" media="screen">
  <%=".#{category.name.delete(' ')}"%> {
    margin-top: 0px;
    margin-bottom: 20px;
    background: <%="#{category.color}"%> !important;
  }
</style>

<%= link_to category, class:"no-color-link" do %>
<div class="col-md-4">
  <div class="card <%= " #{category.name.delete(' ')}" %>">
      <div class="card-body">
        <div class="text-center">
          <%= image_tag category.cat_img(:medium) %>
        </div>
          <em>
            <h2 class="card-title text-center"><%= link_to category.name, category, class:"no-color-link" %></h2>
          </em>
          <p>
              <%= "Contiene #{category.articles.count} artículo(s)" %>
          </p>
          <p>
              <%= "Creado el #{category.created_at.strftime("%d/%m/%Y %H:%M")}" %>
          </p>
          <% if user_signed_in? %>
            <% if current_user.is_admin? || current_user.is_editor? %>
              <div class="text-center">
                <%= link_to  'Editar', edit_category_path(category), class:'btn btn-outline-warning' %>
                <%= link_to 'Eliminar', category, method: :delete, data: {confirm: 'Esta seguro que desea eliminar el articulo?'}, class:'btn btn-outline-danger' %>
              </div>
            <% end %>
          <% end %>
      </div>
  </div>
</div>
<% end %>

app/views/categories/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <br>
      <div class="jumbotron space-a">
          <fieldset>
            <legend class="text-center space-title form-title">
              <%= "#{title} Categoria" %>
            </legend>
            <%= form_with(model: category, local: true) do |form| %>
              <% if category.errors.any? %>
                <div id="error_explanation">
                  <h2>
                    <%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
                  <ul>
                    <% category.errors.full_messages.each do |message| %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="form-group row">
                <%= form.label "Nombre:", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                <%= form.text_field :name, class:"col-md-4 form-control" %>
              </div>

              <div class="form-group row">
                <%= form.label "Banner:", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                <%= form.file_field :cat_img, class:"col-md-4 form-control" %>
              </div>

              <div class="form-group row">
                <%= form.label "Color:", class:"offset-md-2 col-md-3 col-form-label text-right space-label-right" %>
                <%= form.color_field :color, class:"col-md-4 form-control" %>
              </div>

              <div class="form-group row">
                <div class="container text-center">
                  <%= form.submit "Aceptar", class:"btn btn-outline-success col-md-3" %>
                  <%= link_to "Cancelar", :back, class: "btn btn-outline-info col-md-3" %>
                </div>
              </div>
            <% end %>
          </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/categories/admin_category.html.erb
<style type="text/css" media="screen">
  .jumbotron{
    padding-top: 10px !important;
  }
</style>

<div class="jumbotron table-responsive">
  <h1>Administrador</h1>
  <%= link_to  "Cambiar vista", categories_path(cambiar:true), class:"btn btn-info" %>
  <table class="table-responsive">
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-primary">
          <th>Nombre</th>
          <th>Fecha de creación</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |cat| %>
        <tr>
          <td>
            <%= cat.name %>
          </td>
          <td>
            <%= cat.created_at.strftime("%d/%m/%Y %H:%M") %>
          </td>
          <td>
            <%= link_to "Ver", cat, class:"btn btn-outline-info" %>
            <%= link_to "Editar", edit_category_path(cat), class:"btn btn-outline-warning" %>
            <%= link_to "Eliminar", cat, method: :delete, data:{confirm:"Desea eliminar?"}, class:"btn btn-outline-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </table>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category, title:"Editar" %>

app/views/categories/index.html.erb
<div class="row">
  <%= render @categories %>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category, title:"Nueva" %>

app/views/categories/show.html.erb
<style type="text/css" media="screen">
  .jumbotron {
    margin-top: 10px !important;
  }

  .categories-show {
    background: <%= @category.color %> !important;
  }
</style>

<div class="categories-show" style="margin-bottom: 20px;">
  <%= link_to  @category, class:"no-color-link" do %>
    <h1 class="text-center">
      <%= @category.name %>
    </h1>
    <p class="text-center">
      <% if !@category.user.nil? %>
      Creado por: <strong>
        <%= @category.user.email %></strong>
      <% end %>
    </p>
  <% end %>
</div>

<div class="row">
  <%= render @articles %>
</div>
<div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
  <%= will_paginate @articles %>
</div>